name: Render tutorial
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  render-tutorial:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - uses: r-lib/actions/setup-renv@v2
  
      - name: Cache across tutorial builds
        uses: actions/cache@v3
        with:
          path: |
            tutorial_cache
            tutorial_files
          key: cache
  
      - name: Render the README
        run: |
          rmarkdown::render(
            "README.md", output_format = "html_document",
            output_file = "index.html"
          )
        shell: Rscript {0}
  
      - name: Render the tutorial
        run: |
          rmarkdown::render("tutorial.Rmd")
        shell: Rscript {0}
  
      - name: Move files to new folder
        run: |
          mkdir rendered_docs
          mv index.html tutorial.html slides.pdf rendered_docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          retention-days: 5
          path: rendered_docs

  deploy-tutorial:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render-tutorial
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1